# Generated by Django 4.2.1 on 2025-06-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
    ]
