# Generated by Django 4.2.1 on 2025-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0002_remove_orderitem_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid', max_digits=10, null=True),
        ),
    ]
