# Generated by Django 4.2.1 on 2025-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_on'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='all_transaction_info_after_callback',
            field=models.JSONField(blank=True, help_text='This field will be updated after we query the actual tx from pesapal and update transaction status here', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pesapal_order_tracking_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pesapal_redirect_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_init_info',
            field=models.JSONField(blank=True, help_text='Information received from pesapal when the tx was started', null=True),
        ),
    ]
