# Generated by Django 4.2.1 on 2025-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0006_callbackurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackurls',
            name='callback_url_id',
            field=models.TextField(null=True),
        ),
    ]
