# Generated by Django 4.2.1 on 2025-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0007_callbackurls_callback_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackurls',
            name='identifier',
            field=models.CharField(blank=True, default='active', max_length=20),
        ),
    ]
