# Generated by Django 4.2.1 on 2025-06-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0008_callbackurls_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='custom_ecommerce.order'),
        ),
    ]
