# Generated by Django 4.2.1 on 2025-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
