# Generated by Django 4.2.1 on 2025-06-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0012_productcategory_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
