# Generated by Django 4.2.1 on 2025-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_ecommerce', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
